### ISSUE TITLE
scripts.2.0.0.js not available

### ISSUE THREAD

**Issue by achimismaili** [marmind/IdentityServer3.Contrib.Localization.UI#14]
In the _layout.html, there is a js file referenced under assets/scripts.2.0.0.js, but I can not find any js file under assets neither via nuget nor in this repository ...?
Is this file supposed to be generated dynamically?
(I have the same issue as in https://github.com/marmind/IdentityServer3.Contrib.Localization.UI/issues/9, that the screen is blank, so it seems that the js file is not loaded ...?)

**Comment by asilberschneider** [comment]
Fixed with ae815fe, see #9
