### ISSUE TITLE
embeddedViewServiceConfig not defined

### ISSUE THREAD

**Issue by achimismaili** [marmind/IdentityServer3.Contrib.Localization.UI#15]
In the Install description, you suggest to add new DefaultViewService(embeddedViewServiceConfig, new LocalizedViewLoader()), but you don't describe, how embeddedViewServiceConfig is created / configured.

Is it just a simple instance of DefaultViewServiceOptions like the following?
var embeddedViewServiceConfig = new DefaultViewServiceOptions();

**Comment by saidoze** [comment]
That seemed to fix it, yes.

**Comment by asilberschneider** [comment]
Thanks, added to description
