### ISSUE TITLE
Certain view localizations not applied

### ISSUE THREAD

**Issue by petr-k** [marmind/IdentityServer3.Contrib.Localization.UI#4]
Some of the views, including `layout.html`, `welcome.html`, `FormPostResponse.html` are not applied and thus are not localizable. It seems they are incorrectly named since prefixing them with `_` (e.g. `_layout.html`) fixes the issue.

I doubt it's an oversight, so is there a reason for this?

**Comment by norberteder** [comment]
Files renamed. 
Thank you very much for your help :+1:
