### ISSUE TITLE
How can i add another language

### ISSUE THREAD

**Issue by marzoukali** [marmind/IdentityServer3.Contrib.Localization.UI#7]
How can i add another language for example Arabic is it only add another resource file with the language iso code?

**Comment by asilberschneider** [comment]
Yes, have a look at TranslatorHelper.cs:
The exact culture string is searched for first (e.g. "ar-DZ.po") then it falls back to the two letter iso name (e.g. "ar.po"), and if those weren't found it uses "en.po".
