### ISSUE TITLE
blank pages instead of the views

### ISSUE THREAD

**Issue by marzoukali** [marmind/IdentityServer3.Contrib.Localization.UI#9]
I am use the below code:

`var assetsPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "bin" , "assets");
    idServerServiceFactory.ViewService = new Registration<IViewService>(
     resolver => new DefaultViewService(new DefaultViewServiceOptions(), new LocalizedViewLoader(assetsPath)));
`

but when i redirect to the _consent.html i found only a title without any content and in developer tools:

> https://localhost:44304/identity/assets/scripts.2.0.0.js 

Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by solidstore** [comment]
You need to fix the script version in the _layout.html

**Comment by asilberschneider** [comment]
Fixed with ae815fe, see #14
